pwm_node:
  ros__parameters:
    device: "/dev/i2c-1"
    frequency: 50
    address: 0x40
    pwm_min:        [   200,   200, 0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0]
    pwm_max:        [   400,   400, 0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0]
    timeout:        [   200,   200, 0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0]
    timeout_value:  [     0,     0, 0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0]

