<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bringup</name>
  <version>0.0.0</version>
  <description>Launching all relevant nodes for ROS Crawler</description>
  <maintainer email="moritz.boeker@public-files.de">Moritz Boeker</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>foxglove_bridge</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>pwm_pca9685</exec_depend>
  <exec_depend>sparkfun_otos_driver</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>vanjee_lidar_sdk</exec_depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
